Foreground yes
LogTime yes
LogFile /var/log/clamav/clamd.log
LogFileUnlock yes
LogFileMaxSize 2M
LogRotate yes
DatabaseDirectory /var/lib/clamav
LocalSocket /tmp/clamd.sock
FixStaleSocket yes
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
StreamMaxLength 1024M
MaxFileSize 1024M
MaxScanSize 2048M
MaxScanTime 240000
MaxThreads 2
MaxQueue 8
ReadTimeout 300
CommandReadTimeout 30
SendBufTimeout 300
ConcurrentDatabaseReload no
AlertExceedsMax yes
ScanArchive yes
ScanPE yes
ScanELF yes
ScanOLE2 yes
ScanPDF yes
ScanHTML yes
ScanMail yes
