const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('memeroom', {
  info: () => ipcRenderer.invoke('app:info'),
  saveSettings: value => ipcRenderer.invoke('settings:save', value),
  recordShortcut: active => ipcRenderer.invoke('shortcut:record', active),
  saveDismissShortcut: value => ipcRenderer.invoke('shortcut:save', value),
  saveClient: value => ipcRenderer.invoke('client:save', value),
  listPresets: () => ipcRenderer.invoke('presets:list'),
  savePreset: value => ipcRenderer.invoke('presets:save', value),
  renamePreset: (id, name) => ipcRenderer.invoke('presets:rename', id, name),
  removePreset: id => ipcRenderer.invoke('presets:remove', id),
  loadPreset: (id, server, token) => ipcRenderer.invoke('presets:load', id, server, token),
  show: value => ipcRenderer.invoke('overlay:show', value),
  test: () => ipcRenderer.invoke('overlay:test'),
  clear: () => ipcRenderer.send('overlay:clear'),
  minimize: () => ipcRenderer.invoke('app:minimize'),
  restart: () => ipcRenderer.invoke('app:restart'),
  listSavedMemes: () => ipcRenderer.invoke('savedMemes:list'),
  openSavedMemesFolder: () => ipcRenderer.invoke('savedMemes:openFolder'),
  openSavedMemeFile: name => ipcRenderer.invoke('savedMemes:openFile', name),
  deleteSavedMeme: name => ipcRenderer.invoke('savedMemes:delete', name),
  renameSavedMeme: (oldName, newName) => ipcRenderer.invoke('savedMemes:rename', oldName, newName),
  readSavedMeme: name => ipcRenderer.invoke('savedMemes:read', name),
  trimMedia: options => ipcRenderer.invoke('media:trim', options),
  extractAudio: options => ipcRenderer.invoke('media:extractAudio', options),
  loadHistory: () => ipcRenderer.invoke('history:load'),
  saveHistory: list => ipcRenderer.invoke('history:save', list),
  onSavedMemesUpdated: callback => { ipcRenderer.on('savedMemes:updated', () => callback()); },
  onSettings: callback => { ipcRenderer.on('settings:changed', (_event, value) => callback(value)); },
  onError: callback => { ipcRenderer.on('overlay:error', (_event, value) => callback(value)); }
});
